### ISSUE TITLE
Custom element support

### ISSUE THREAD

**Issue by makma** [Kentico/kontent-java-packages#77]
### Motivation

In the upcoming days/weeks there will be new element type (custom element) in the Delivery output.
This will cause the failure of model binding since it's not included in the known type ids.
`known type ids = [Element, asset, date_time, modular_content, multiple_choice, number, rich_text, taxonomy, text, url_slug]`

`com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'custom' into a subtype of [simple type, class com.kenticocloud.delivery.Element]: known type ids = [Element, asset, date_time, modular_content, multiple_choice, number, rich_text, taxonomy, text, url_slug]
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.kenticocloud.delivery.ContentItemResponse["item"]->com.kenticocloud.delivery.ContentItem["elements"]->java.util.LinkedHashMap["ahojky"])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:42)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeIdException(DeserializationContext.java:1477)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1170)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:282)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:112)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:519)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
	at com.kenticocloud.delivery.AsyncDeliveryClient.putInCache(AsyncDeliveryClient.java:469)
	at com.kenticocloud.delivery.AsyncDeliveryClient.lambda$executeRequest$12(AsyncDeliveryClient.java:388)
	at `

It should be supported in generator as well.

### Proposed solution

Add custom element into `known type ids` and ensure the binding won't fail in the future when new element type is added.

For generator add new case and handling in 

> public JavaFile generateSource(ContentType type)

### Additional context

Expected Delivery output:

>
.
.
.
"elements": {
.
.
.
  "title": {
    "type": "text",
    "name": "Title",
    "value": "Shiny Globe"
  },
   .
   .
   .
  **"colorPicker": {
    "type": "custom_field",
    "name": "Color_Picker",
    "value": "#4286f4"
   },**
    .
    .
    .
.
.
.

**Comment by makma** [comment]
Note: We have an estimated time of releasing this feature in the fourteen days. Do you @aweigold  think you'll be able to introduce fix (feature) or should we look for other resources? Thank you!

**Comment by aweigold** [comment]
I'll take a look over this weekend.  I assume the changing API is documented somewhere?

**Comment by makma** [comment]
Hi Adam, one of our teams is still finalizing the design of the API moreover, I'll let you know as soon as the final decision is made. Thank you!

**Comment by aweigold** [comment]
@makma I'm a bit concerned.  If this is a breaking API change, to be released in less than 2 weeks, and the API isn't documented, won't all consumers immediately be affected with outages?  Even with an update turned around in that time, ensuring all consumers update their dependencies in time seems risky to me.

**Comment by aweigold** [comment]
@makma Can you attach some sample responses?  We can mitigate by configuring Jackson to not fail on unknown properties until the specification is documented.

Pinging @petrsvihlik @JanLenoch

**Comment by makma** [comment]
Hi @aweigold ,
we will release 'Custom elements' as a beta feature and one will have to enable this feature explicitly in the Kentico Cloud UI (probably in Content models). Before enabling the feature, the user will be informed with all the consequences. The important thing is, the output of the Delivery API won't be affected until it's explicitly enabled by the user - this means the output of the API will be the same even after the release of this feature, as a result, no existing projects could be affected.

If the user enables the feature and uses the 'Custom element' in the item, the output will contain the new [element](https://developer.kenticocloud.com/reference#content-type-element-object) object with a type attribute's value `custom_field`.

The elements object will contain a new element of `custom_field` type:

```
"myCustomElement": {
  "type": "custom_field",
  "name": "name_of_my_element",
  "value": "my_value"
},
```

Does it make sense to you?

**Comment by aweigold** [comment]
Sounds excellent.

**Comment by petrsvihlik** [comment]
More context:
- https://developer.kenticocloud.com/reference#custom-elements-api
- https://developer.kenticocloud.com/docs/integrating-content-editing-features
